
[REQ-lvl-1]
partof = "REQ-purpose"

text = "one level deep in a recursive dir"

[SPC-lvl-1]
text = "level one does FOO"

[SPC-loc-dne]
text = "dne does not exist"

[SPC-loc]
text = "test that it goes into a src directory"
