[REQ-bar]

[REQ-escape]
text = '''
here are some escaped characters:
 - \n
 - \r
 - \w
 - \f
 - \t
 - \"
 - \'
'''

[REQ-foo]
partof = "REQ-purpose"
text = "this is a single line with spaces   "

[REQ-graph]
text = '''
This has some backslashes

*from*           `where`
   |                |
   \----> there <---/ 

Adds tons of fun characters
'''

[REQ-purpose]
text = '''
The purpose of this project is...
'''

[REQ-quotes]
text = '''
This has quotes in it, which don't change

"whoo"
'and single quotes'
'''

[SPC-all]
partof = "SPC-[bar, baz, foo]"

[SPC-bar]

[SPC-baz]

[SPC-foo]
